language: python
install: "pip install nose nose-cov coverage coveralls"
script: nosetests --verbosity=2 && coverage report --fail-under=100
after_success: coveralls

notifications:
    email:
        on_success: always
        on_failure: always
