language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
  pip install -r requirements-optional.txt
script:
  make test-all
after_success:
  coveralls
notifications:
    email:
        on_success: always
        on_failure: always
