language: python
install: "pip install nose nose-cov"
script: nosetests --verbosity=2 --with-coverage --cover-package fauxfactory tests/

notifications:
    email:
        on_success: always
        on_failure: always