language: python
install: "pip install nose nose-cov coveralls"
script: nosetests --verbosity=2 --with-coverage --cover-package fauxfactory tests/
after_success: coveralls --base_dir fauxfactory

notifications:
    email:
        on_success: always
        on_failure: always
